server:
  port: 8082
spring:
  application:
    name: consumer # 应用名称

eureka:
  client:
    service-url:
      defaultzone: http://127.0.0.1:8761/eureka  #Eureka 服务地址
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找